name: Build and Deploy Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      # این مرحله چون پوشه web در ریپازیتوری وجود ندارد اضافه شده است.
      - name: Generate missing platform files (web)
        run: flutter create --platforms=web .

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href /construction-app/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
